# Generated by Django 4.1.2 on 2023-02-18 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('qte_gazoil', models.IntegerField()),
                ('date_recharge', models.DateTimeField(auto_now_add=True)),
                ('qte_chlore', models.IntegerField()),
                ('qte_filtre_air', models.IntegerField()),
                ('date_rplment_fitre_air', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.site')),
            ],
            options={
                'verbose_name': 'Collecte de site',
                'verbose_name_plural': 'Collectes de site',
            },
        ),
        migrations.CreateModel(
            name='CustomerCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Index')),
                ('image', models.ImageField(upload_to='collecte/abonne', verbose_name='Image')),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.abonne', verbose_name='Client')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Collecte Client',
                'verbose_name_plural': 'Collectes Client',
            },
        ),
    ]
