# Generated by Django 4.1.7 on 2023-03-26 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_agence_commune_abonne_commune_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collecte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.site')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Nom du parametre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SettingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Nom du parametre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'SettingSite',
                'verbose_name_plural': 'SettingSites',
            },
        ),
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_in_site', models.FloatField(blank=True, null=True)),
                ('humidity_in_site', models.FloatField(blank=True, null=True)),
                ('chlore_in_site', models.FloatField(blank=True, null=True)),
                ('ph_out_site', models.FloatField(blank=True, null=True)),
                ('humidity_out_site', models.FloatField(blank=True, null=True)),
                ('chlore_out_site', models.FloatField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'WaterQuality',
                'verbose_name_plural': 'WaterQualitys',
            },
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='date_collecte',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='date_recharge',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='date_rplment_fitre_air',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='qte_chlore',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='qte_filtre_air',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='qte_gazoil',
        ),
        migrations.AddField(
            model_name='customercollecte',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecollecte',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='sitecollecte',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customercollecte',
            name='abonne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.abonne', verbose_name='Client'),
        ),
        migrations.CreateModel(
            name='SiteCollecteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=254, verbose_name='Valuer du paremetre')),
                ('is_exist', models.BooleanField(default=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collecte.settingsite')),
                ('site_collecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collecte.sitecollecte')),
            ],
            options={
                'verbose_name': 'SiteCollecteDetail',
                'verbose_name_plural': 'SiteCollecteDetails',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=254, verbose_name='Valuer du paremetre')),
                ('is_exist', models.BooleanField(default=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collecte.maintenance')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collecte.setting')),
            ],
            options={
                'verbose_name': 'MaintenanceDetail',
                'verbose_name_plural': 'MaintenanceDetails',
            },
        ),
        migrations.CreateModel(
            name='CollectOnSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solaire', models.CharField(max_length=100, null=True)),
                ('groupe_electro', models.CharField(max_length=100, null=True)),
                ('index', models.IntegerField(null=True)),
                ('production', models.CharField(max_length=100, null=True)),
                ('sbee', models.CharField(max_length=100, null=True)),
                ('observation', models.TextField(null=True)),
                ('nbre_panne', models.IntegerField(null=True)),
                ('description_panne', models.TextField(null=True)),
                ('production_estimer', models.CharField(max_length=100, null=True)),
                ('autres', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.site')),
                ('water_quality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collecte.waterquality')),
            ],
            options={
                'verbose_name': 'CollectOnSite',
                'verbose_name_plural': 'CollectOnSites',
            },
        ),
    ]
