# Generated by Django 4.1.7 on 2023-03-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0002_maintenance_setting_settingsite_waterquality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectonsite',
            name='production',
        ),
    ]
