# Generated by Django 4.1.2 on 2023-02-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('collecte', '0002_sitecollecte_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecollecte',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.site'),
        ),
    ]
