# Generated by Django 4.1.7 on 2023-03-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0003_remove_collectonsite_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametersWaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('chlore', models.FloatField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
