# Generated by Django 4.1.2 on 2023-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0003_alter_sitecollecte_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecollecte',
            name='date_collecte',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitecollecte',
            name='date_recharge',
            field=models.DateField(auto_now=True),
        ),
    ]
