# Generated by Django 4.1.2 on 2023-02-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0005_alter_sitecollecte_date_rplment_fitre_air'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecollecte',
            name='date_recharge',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sitecollecte',
            name='date_rplment_fitre_air',
            field=models.DateField(),
        ),
    ]
