# Generated by Django 4.1.2 on 2023-02-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0007_setting_customercollecte_date_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
