# Generated by Django 4.1.2 on 2023-02-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_abonne_date_ajout'),
        ('collecte', '0010_maintenance_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Nom du parametre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'SettingSite',
                'verbose_name_plural': 'SettingSites',
            },
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='date_collecte',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='date_recharge',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='date_rplment_fitre_air',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='qte_chlore',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='qte_filtre_air',
        ),
        migrations.RemoveField(
            model_name='sitecollecte',
            name='qte_gazoil',
        ),
        migrations.AddField(
            model_name='sitecollecte',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecollecte',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.site'),
        ),
        migrations.CreateModel(
            name='SiteCollecteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=254, verbose_name='Valuer du paremetre')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collecte.settingsite')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.site')),
            ],
            options={
                'verbose_name': 'SiteCollecteDetail',
                'verbose_name_plural': 'SiteCollecteDetails',
            },
        ),
    ]
