# Generated by Django 4.1.2 on 2023-02-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0011_settingsite_remove_sitecollecte_date_collecte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecollectedetail',
            name='site',
        ),
        migrations.AddField(
            model_name='sitecollectedetail',
            name='site_collecte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collecte.sitecollecte'),
        ),
    ]
