# Generated by Django 4.1.2 on 2023-02-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_abonne_date_ajout'),
        ('collecte', '0012_remove_sitecollectedetail_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercollecte',
            name='abonne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.abonne', verbose_name='Client'),
        ),
    ]
