# Generated by Django 4.1.2 on 2023-03-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0015_waterquality_collectonsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectonsite',
            old_name='produit_traitement',
            new_name='production',
        ),
        migrations.AlterField(
            model_name='collectonsite',
            name='description_panne',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collectonsite',
            name='nbre_panne',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collectonsite',
            name='observation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collectonsite',
            name='production_estimer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectonsite',
            name='water_quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collecte.waterquality'),
        ),
    ]
