# Generated by Django 4.1.2 on 2023-03-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0016_rename_produit_traitement_collectonsite_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectonsite',
            name='autres',
            field=models.TextField(null=True),
        ),
    ]
