# Generated by Django 4.1.2 on 2023-03-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_agence_commune_abonne_commune_and_more'),
        ('collecte', '0017_collectonsite_autres'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectonsite',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.site'),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='chlore_in_site',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='chlore_out_site',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='humidity_in_site',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='humidity_out_site',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='ph_in_site',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='ph_out_site',
            field=models.IntegerField(null=True),
        ),
    ]
