# Generated by Django 4.1.2 on 2023-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0018_collectonsite_site_alter_waterquality_chlore_in_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectonsite',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
