# Generated by Django 4.1.2 on 2023-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0019_collectonsite_date_waterquality_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterquality',
            name='chlore_in_site',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='chlore_out_site',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='humidity_in_site',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='humidity_out_site',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='ph_in_site',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='ph_out_site',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
