# Generated by Django 4.1.2 on 2023-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0020_alter_waterquality_chlore_in_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterquality',
            name='chlore_in_site',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='chlore_out_site',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='humidity_in_site',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='humidity_out_site',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='ph_in_site',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='ph_out_site',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
