# Generated by Django 4.1.2 on 2023-02-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonne',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
