# Generated by Django 4.1.2 on 2023-03-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
        ('app', '0003_agence_commune_agence_departement_site_commune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='commune',
        ),
        migrations.AddField(
            model_name='abonne',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agence.commune'),
        ),
        migrations.AddField(
            model_name='abonne',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agence.departement'),
        ),
    ]
