# Generated by Django 4.1.2 on 2023-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_agence_commune_abonne_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'StatusAb',
                'verbose_name_plural': 'StatusAbs',
            },
        ),
    ]
