# Generated by Django 4.1.2 on 2023-04-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_statusab'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonne',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.statusab'),
        ),
    ]
