# Generated by Django 4.1.2 on 2023-02-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ManyToManyField(blank=True, to='app.site', verbose_name='Site'),
        ),
    ]
